<template>
  <q-form class="col q-ma-md q-gutter-y-md">
    <q-editor
      v-model="itemDescricao"
      min-height="5rem"
      placeholder="Descrição"
    />
    <q-select
      outlined
      v-model="setorAtual"
      :options="setorLista"
      label="Setor"
    />
    <q-select
      outlined
      v-model="dependenciaAtual"
      :options="dependenciaLista"
      label="Dependência"
    />
    <q-input outlined v-model="empenho" label="Empenho" />
    <q-select
      outlined
      v-model="estadoPlaquetaAtual"
      :options="estadoPlaquetaLista"
      label="Estado da plaqueta"
    />
    <q-input outlined v-model="nomeFornecedor" label="Fornecedor" />
    <q-editor
      v-model="itemLocalizacao"
      min-height="5rem"
      placeholder="Localização"
    />
    <q-editor
      v-model="itemObservacao"
      min-height="5rem"
      placeholder="Observação"
    />
    <q-input outlined v-model="patrimonio" label="Patrimônio" />
    <q-select
      outlined
      v-model="situacaoAtual"
      :options="situacaoLista"
      label="Situação"
    />
    <q-input outlined disabled v-model="usuario" label="Usuário" />
  </q-form>
</template>

<script setup>
import { ref, defineProps, onMounted, onUpdated } from "vue";

const itemDescricao = ref("");
const setorAtual = ref("");
const setorLista = ref([]);
const dependenciaAtual = ref("");
const dependenciaLista = ref([]);
const empenho = ref("");
const estadoPlaquetaAtual = ref("");
const estadoPlaquetaLista = ref([]);
const nomeFornecedor = ref("");
const itemLocalizacao = ref("");
const itemObservacao = ref("");
const patrimonio = ref([]);
const situacaoAtual = ref("");
const situacaoLista = ref([]);
const usuario = ref("");
const props = defineProps({ id: Number });

onMounted(() => {
  const item = buscarItemPorId(props.id);
  itemDescricao.value = item.descricao;
});

onUpdated(() => {
  const item = buscarItemPorId(props.id);
  itemDescricao.value = item.descricao;
});

function buscarItemPorId(id) {
  return itemsColetados.value.find((i) => i.id === id);
}
// deletar
const itemsColetados = ref([
  {
    id: 78,
    item: 6,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000077",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 77",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 1,
    item: 22,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000000",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao: "Inventário do item gerado automaticamente par teste. Número 0",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 46,
    item: 36,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000045",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 45",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 58,
    item: 47,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000057",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 57",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 47,
    item: 91,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000046",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 46",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 3,
    item: 106,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000002",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao: "Inventário do item gerado automaticamente par teste. Número 2",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 79,
    item: 106,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000078",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 78",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 15,
    item: 164,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000014",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 14",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 65,
    item: 177,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000064",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 64",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 41,
    item: 185,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000040",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 40",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 34,
    item: 188,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000033",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 33",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 80,
    item: 202,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000079",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 79",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 82,
    item: 239,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000081",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 81",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 96,
    item: 241,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000095",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 95",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 90,
    item: 246,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000089",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 89",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 62,
    item: 261,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000061",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 61",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 99,
    item: 270,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000098",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 98",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 70,
    item: 278,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000069",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 69",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 98,
    item: 283,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000097",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 97",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 71,
    item: 291,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000070",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 70",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 51,
    item: 295,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000050",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 50",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 13,
    item: 301,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000012",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 12",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 68,
    item: 304,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000067",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 67",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 94,
    item: 312,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000093",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 93",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 33,
    item: 320,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000032",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 32",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 81,
    item: 322,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000080",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 80",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 37,
    item: 328,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000036",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 36",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 97,
    item: 329,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000096",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 96",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 73,
    item: 366,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000072",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 72",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 40,
    item: 393,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000039",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 39",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 2,
    item: 394,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000001",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao: "Inventário do item gerado automaticamente par teste. Número 1",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 28,
    item: 397,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000027",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 27",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 100,
    item: 404,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000099",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 99",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 16,
    item: 415,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000015",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 15",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 76,
    item: 433,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000075",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 75",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 7,
    item: 442,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000006",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao: "Inventário do item gerado automaticamente par teste. Número 6",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 67,
    item: 448,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000066",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 66",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 69,
    item: 453,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000068",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 68",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 92,
    item: 453,
    inventario: 1,
    dependencia: 1,
    departamento: 1,
    patrimonio: "000091",
    fornecedor: "",
    empenho: "",
    identificador: "123456789",
    descricao: "",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 91",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 21,
    item: 481,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000020",
    fornecedor: "CIRURGICA AGALMA LTDA",
    empenho: "2012NE801110",
    identificador: "123456789",
    descricao:
      "CAIXA PARA ARMAZENAGEM DE LÂMINAS HISTOLÓGICAS. CAPACIDADE DE 100 LÂMINAS, MATERIAL: MADEIRA ENVERNIZADA OU POLIPROPILENO RÍGIDO, COM BORDAS ARREDONDADAS OU SEM REBARBAS CORTANTES. PARA LÂMINAS DE DIM...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 20",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 95,
    item: 502,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000094",
    fornecedor: "CIRURGICA AGALMA LTDA",
    empenho: "2012NE801110",
    identificador: "123456789",
    descricao:
      "CAIXA PARA ARMAZENAGEM DE LÂMINAS HISTOLÓGICAS. CAPACIDADE DE 100 LÂMINAS, MATERIAL: MADEIRA ENVERNIZADA OU POLIPROPILENO RÍGIDO, COM BORDAS ARREDONDADAS OU SEM REBARBAS CORTANTES. PARA LÂMINAS DE DIM...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 94",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 60,
    item: 509,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000059",
    fornecedor: "COMERCIO DE MATERIAIS MEDICOS HOSPITALARES MACROSUL LTDA",
    empenho: "2012NE801360",
    identificador: "123456789",
    descricao:
      "ESFIGMOMANÔMETRO, TIPO ANERÓIDE, COMPONENTES BRAÇADEIRA, MANGUITO, PERA, VÁLVULA COM ROSCA, CAPACIDADE MEDIDA DE 0 A 300 MM/HG, CARACTERÍSTICAS ADICIONAIS COM ESTOJO E BRAÇADEIRA COM FECHO DE VELCRO, ...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 59",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 9,
    item: 527,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000008",
    fornecedor: "PG OFFICE COMERCIO DE MOVEIS LTDA",
    empenho: "2012NE802064",
    identificador: "123456789",
    descricao:
      "CADEIRA GIRATÓRIA, ESPALDAR MÉDIO, COM BRAÇOS. CONFECCIONADA COM ASSENTO E ENCOSTO EM CHASSIS DE MADEIRA COMPENSADA, MULTILAMINADA, MOLDADA ANATOMICAMENTE COM ESPESSURA DE 12MM. ESTOFAMENTO EM ESPUMA ...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao: "Inventário do item gerado automaticamente par teste. Número 8",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 31,
    item: 544,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000030",
    fornecedor: "COPY CENTER COMERCIO PRODUTOS INFORMATICA LTDA",
    empenho: "2012NE802238",
    identificador: "123456789",
    descricao:
      "IMPRESSORA MULTIFUNCIONAL LASER MONOCROMÁTICA (IMPRESSORA, DIGITALIZADORA, COPIADORA E FAX). PROCESSADOR MÍNIMO DE 360 MHZ, MEMÓRIA MÍNIMA DE 64 MB, BANDEJA DE ENTRADA PARA NO MÍNIMO 150 FOLHAS. IMPRE...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 30",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 84,
    item: 566,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000083",
    fornecedor: "PORT DISTRIBUIDORA DE INFORMATICA E PAPELARIA LTDA",
    empenho: "2013NE802371",
    identificador: "123456789",
    descricao:
      "IMPRESSORA MULTIFUNCIONAL JATO DE TINTA COLORIDA (IMPRESSORA, DIGITALIZADORA, COPIADORA E FAX). PROCESSADOR MÍNIMO DE 190 MHZ, MEMÓRIA MÍNIMA DE 64 MB, BANDEJA DE ENTRADA PARA NO MÍNIMO 100 FOLHAS. IM...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 83",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 39,
    item: 587,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000038",
    fornecedor: "MICROTECNICA INFORMATICA LTDA.",
    empenho: "2013NE802335",
    identificador: "123456789",
    descricao:
      "NOTEBOOK. PROCESSADOR 3.4 GHZ TURBO MAX OU SUPERIOR, MÍN. 6 MB L2 INTELIGENTE, COM TECNOLOGIA TURBO BOOST. 6 GB DE MEMÓRIA RAM DDR3 1066 MHZ OU SUP. (EXPANSÍVEL MINIMO ATÉ 8 GB). DISCO RÍGIDO DE 500 G...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 38",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 35,
    item: 612,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000034",
    fornecedor: "K.S. ARTIGOS ESPORTIVOS - EIRELI - ME",
    empenho: "2014NE802106",
    identificador: "123456789",
    descricao:
      "PESO DE ATLETISMO DE AÇO 6,00 KG PARA ARREMESSO, ACABAMENTO RÍGIDO DE AÇO GALVANIZADO E PINTADO. NÚCLEO DE CHUMBO. PESO PRECISO, FORMATO ESFÉRICO E EQUILÍBRIO PERFEITOS. SUPERFÍCIE TOTALMENTE LISA. PE...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 34",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 64,
    item: 621,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000063",
    fornecedor: "BOM JARDIM VAREJO DE CALCADOS EIRELI EPP",
    empenho: "2014NE802105",
    identificador: "123456789",
    descricao:
      "DARDO DE ALUMÍNIO/AÇO 500 G. PARA TREINAMENTO. ESTRUTURA DE ALUMÍNIO, CABEÇA DE AÇO, EMPUNHADURA DE CORDA E CALDA AFINADA.",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 63",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 48,
    item: 622,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000047",
    fornecedor: "BOM JARDIM VAREJO DE CALCADOS EIRELI EPP",
    empenho: "2014NE802105",
    identificador: "123456789",
    descricao:
      "DARDO DE BAMBU 400 G.  EMPUNHADURA DE CORDEL E PONTEIRA DE FERRO (PINTADA).",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 47",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 44,
    item: 627,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000043",
    fornecedor: "BOM JARDIM VAREJO DE CALCADOS EIRELI EPP",
    empenho: "2014NE802105",
    identificador: "123456789",
    descricao:
      "DARDO DE BAMBU 400 G.  EMPUNHADURA DE CORDEL E PONTEIRA DE FERRO (PINTADA).",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 43",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 55,
    item: 628,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000054",
    fornecedor: "BOM JARDIM VAREJO DE CALCADOS EIRELI EPP",
    empenho: "2014NE802105",
    identificador: "123456789",
    descricao:
      "DARDO DE BAMBU 400 G.  EMPUNHADURA DE CORDEL E PONTEIRA DE FERRO (PINTADA).",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 54",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 14,
    item: 629,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000013",
    fornecedor: "BOM JARDIM VAREJO DE CALCADOS EIRELI EPP",
    empenho: "2014NE802105",
    identificador: "123456789",
    descricao:
      "DARDO DE BAMBU 400 G.  EMPUNHADURA DE CORDEL E PONTEIRA DE FERRO (PINTADA).",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 13",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 72,
    item: 676,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000071",
    fornecedor: "FRATELLI COM DE MAQ E EQUIPAMENTOS LTDA",
    empenho: "2014NE802195",
    identificador: "123456789",
    descricao:
      "ARMÁRIO PARA ARMAZENAMENTO DE BRINQUEDOS. ARMÁRIO GRANDE COM ESTRUTURA EM CHAPA DE AÇO. POSSUI 5 PRATELEIRAS (SUPORTAM 60KG CADA). 2 PORTAS, FECHAMENTO COM CHAVE. 4 PÉS NIVELADORES. CANTOS ARREDONDADO...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 71",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 8,
    item: 695,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000007",
    fornecedor: "MICROTECNICA INFORMATICA LTDA.",
    empenho: "2014NE802896",
    identificador: "123456789",
    descricao:
      "NOTEBOOK. PROCESSADOR 2.4 GHZ OU SUPERIOR, MÍN. 3 MB CACHE INTELIGENTE, 4 GB DE MEMÓRIA RAM DDR3 1600 MHZ OU SUP.  DISCO RÍGIDO DE 500GB  SATA OU SUP., TELA LED DE 14 POL WIDESCREEN, ANTI REFLEXO, SUP...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao: "Inventário do item gerado automaticamente par teste. Número 7",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 23,
    item: 719,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000022",
    fornecedor: "ALL WORK COMERCIAL - EIRELI - EPP",
    empenho: "2015NE801388",
    identificador: "123456789",
    descricao:
      "COR DO COURVIN: PRETO. MARCA: ARKTUS ; LIMITE DE PESO: 135 KG; LARGURA: 60 CM; ALTURA: 82 CM; COURVIN NAÚTICO SINTÉTICO; ESPUMA ORTOPÉDICA COM DENSIDADE 33; PRODUZIDA EM MADEIRA EUCALYPTUSGRANDIS; COM...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 22",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 75,
    item: 723,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000074",
    fornecedor: "ALL WORK COMERCIAL - EIRELI - EPP",
    empenho: "2015NE801388",
    identificador: "123456789",
    descricao:
      "COR DO COURVIN: PRETO. MARCA: ARKTUS ; LIMITE DE PESO: 135 KG; LARGURA: 60 CM; ALTURA: 82 CM; COURVIN NAÚTICO SINTÉTICO; ESPUMA ORTOPÉDICA COM DENSIDADE 33; PRODUZIDA EM MADEIRA EUCALYPTUSGRANDIS; COM...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 74",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 89,
    item: 724,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000088",
    fornecedor: "ALL WORK COMERCIAL - EIRELI - EPP",
    empenho: "2015NE801388",
    identificador: "123456789",
    descricao:
      "COR DO COURVIN: PRETO. MARCA: ARKTUS ; LIMITE DE PESO: 135 KG; LARGURA: 60 CM; ALTURA: 82 CM; COURVIN NAÚTICO SINTÉTICO; ESPUMA ORTOPÉDICA COM DENSIDADE 33; PRODUZIDA EM MADEIRA EUCALYPTUSGRANDIS; COM...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 88",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 52,
    item: 738,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000051",
    fornecedor: "ATLANTIS COM. DE MAQUINAS E EQUIPAMENTOS EIRELI - EPP",
    empenho: "2015NE801389",
    identificador: "123456789",
    descricao:
      "VIBRADOR DE GESSO ODONTOLÓGICO. MESA REMOVÍVEL PARA FACILITAR A LIMPEZA. ELIMINA BOLHAS DE AR, COM EFEITOS VIBRATÓRIOS NOS MATERIAIS DE MOLDAGEM E REVESTIMENTO DE GESSO. 110/220V. VENTOSAS PARA MELHOR...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 51",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 57,
    item: 744,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000056",
    fornecedor: "ACI COMERCIO EIRELI",
    empenho: "2015NE801335",
    identificador: "123456789",
    descricao:
      "BIOMBO HOSPITALAR, ESTRUTURA TUBULAR, CROMADO, DOBRÁVEL COM RODÍZIOS E 3 FACES. MEDIDAS APROXIMADAS: ALTURA 1.600MM, LARGURA 1.800MM.",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 56",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 91,
    item: 777,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000090",
    fornecedor: "ARMAZENA INDÚSTRIA DE MÓVEIS LTDA EPP",
    empenho: "2016NE800197",
    identificador: "123456789",
    descricao:
      "ACABAMENTO FRONTAL COMPOSTO POR FECHAMENTOS SUPERIOR E INFERIOR, EM CHAPA NÚMERO 24 (0,60 MM) E NÚMERO 20 (0,90 MM) NO MÍNIMO. ITENS DA ESTRUTURA FIXADOS ATRAVÉS DE SOLDA E/OU REBITES DE ALUMÍNIO NO S...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 90",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 49,
    item: 823,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000048",
    fornecedor: "INOVART COMERCIO DE EQUIPAMENTOS EIRELI - EPP",
    empenho: "2016NE801303",
    identificador: "123456789",
    descricao:
      "BANCO SUECO OFICIAL, CONFECCIONADO EM MADEIRA MACIÇA, ENVERNIZADO NA COR MOGNO BRILHANTE OU TRANSPARENTE, NA MEDIDA 3M, COM TRAVE DE EQUILÍBRIO.",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 48",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 88,
    item: 837,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000087",
    fornecedor: "INFORSHOP SUPRIMENTOS LTDA",
    empenho: "2016NE801924",
    identificador: "123456789",
    descricao:
      "IMPRESSORA LASER MONOCROMÁTICA. PROCESSADOR MÍNIMO DE 750 MHZ, MEMÓRIA MÍNIMA DE 128 MB, VELOCIDADE MÍNIMA DE 26 PPM (EM PAPEL CARTA), ENTRADA PAPEL MINIMO 250FOLHAS, SAIDA PARA NO MÍNIMO DE 150FOLHAS...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 87",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 25,
    item: 851,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000024",
    fornecedor: "BRASFITNESS COMERCIO DE ARTIGOS ESPORTIVOS LTDA - ME",
    empenho: "2016NE801291",
    identificador: "123456789",
    descricao:
      "LIMITE DE PESO A CADA 2 PRATELEIRAS: 10KG. ; 12 PRATELEIRAS PARA HALTERES, SENDO EM 6 CADA LADO DO SUPORTE; SUPORTE DUPLO PARA HALTERES: ESTRUTURA EM AÇO DE CARBONO COM PINTURA EPÓXI",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 24",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 30,
    item: 858,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000029",
    fornecedor:
      "FELIPE ELIAS DOS SANTOS REPR. COMERCIAL DE ART. MÉDICOS EIRELI - ME",
    empenho: "2016NE801565",
    identificador: "123456789",
    descricao:
      " CADEIRA DE RODAS. FABRICADA EM TUBOS DE AÇO CARBONO COM ASSENTO EM NYLON DUPLO REFORÇADO COM LONA E ENCOSTO EM NYLON DUPLO ALMOFADADO, COM ALMOFADA DE 4CM NO ASSENTO, COM PROTETOR DE ROUPA, DOBRÁVEL ...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 29",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 6,
    item: 864,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000005",
    fornecedor: "MICROSENS LTDA",
    empenho: "2016NE801928",
    identificador: "123456789",
    descricao:
      "IMPRESSORA MULTIFUNCIONAL LASER MONOCROMÁTICA (IMPRESSORA, DIGITALIZADORA, COPIADORA E FAX). PROCESSADOR MÍNIMO DE 600 MHZ, MEMÓRIA MÍNIMA DE 128 MB, BANDEJA DE ENTRADA PARA NO MÍNIMO 150 FOLHAS. IMPR...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao: "Inventário do item gerado automaticamente par teste. Número 5",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 74,
    item: 868,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000073",
    fornecedor: "MICROSENS LTDA",
    empenho: "2016NE801928",
    identificador: "123456789",
    descricao:
      "IMPRESSORA MULTIFUNCIONAL LASER MONOCROMÁTICA (IMPRESSORA, DIGITALIZADORA, COPIADORA E FAX). PROCESSADOR MÍNIMO DE 600 MHZ, MEMÓRIA MÍNIMA DE 128 MB, BANDEJA DE ENTRADA PARA NO MÍNIMO 150 FOLHAS. IMPR...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 73",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 77,
    item: 892,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000076",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 76",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 83,
    item: 923,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000082",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 82",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 24,
    item: 954,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000023",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 23",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 42,
    item: 983,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000041",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 41",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 93,
    item: 1001,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000092",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 92",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 22,
    item: 1013,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000021",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 21",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 12,
    item: 1027,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000011",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 11",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 63,
    item: 1027,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000062",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 62",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 85,
    item: 1035,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000084",
    fornecedor: "",
    empenho: "2017NE800637",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA, PARA LABORATORIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIAMETRO APROXIMADO DE 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA O...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 84",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 36,
    item: 1079,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000035",
    fornecedor: "CREATIVE INFORMATICA LTDA - EPP",
    empenho: "2016NE801921",
    identificador: "123456789",
    descricao:
      "NOTEBOOK. PROCESSADOR 3.0 GHZ EM TURBO MAX OU SUPERIOR, MÍN. 4 MB CACHE INTELIGENTE, COM TECNOLOGIA TURBO BOOST, 22NM OU 14NM. 8 GB DE MEMÓRIA RAM DDR3 1600 MHZ OU SUP.  DISCO RÍGIDO DE 1TB SATA OU SU...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 35",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 32,
    item: 1083,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000031",
    fornecedor: "GNATUS EQUIPAMENTOS MEDICO ODONTOLOGICOS LTDA",
    empenho: "2016NE801853",
    identificador: "123456789",
    descricao:
      "LOCALIZADOR APICAL COMPUTADORIZADO PARA TRATAMENTO DE CANAL. MARCA: GNATUS",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 31",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 54,
    item: 1088,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000053",
    fornecedor: "GNATUS EQUIPAMENTOS MEDICO ODONTOLOGICOS LTDA",
    empenho: "2016NE801853",
    identificador: "123456789",
    descricao:
      "REFLETOR DUPLO DE BANCADA COM DUPLO CABEÇOTE, LUZ BRANCA, FONTE DE LUZ LED, BRAÇOS ARTICULADOS POSSIBILITANDO FÁCIL AJUSTE DO POSICIONAMENTO, PUXADORES BILATERAIS EM FORMA DE ALÇA. CABEÇOTE COM ESPELH...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 53",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 19,
    item: 1102,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000018",
    fornecedor: "GNATUS EQUIPAMENTOS MEDICO ODONTOLOGICOS LTDA",
    empenho: "2016NE801853",
    identificador: "123456789",
    descricao:
      "REFLETOR DUPLO DE BANCADA COM DUPLO CABEÇOTE, LUZ BRANCA, FONTE DE LUZ LED, BRAÇOS ARTICULADOS POSSIBILITANDO FÁCIL AJUSTE DO POSICIONAMENTO, PUXADORES BILATERAIS EM FORMA DE ALÇA. CABEÇOTE COM ESPELH...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 18",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 10,
    item: 1143,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000009",
    fornecedor: "PEZANI COMÉRCIO DE MÓVEIS EIRELI ME",
    empenho: "2017NE801976",
    identificador: "123456789",
    descricao:
      "BANQUETA PARA MESA DE DESENHO, FABRICADA EM MADEIRA ADEQUADA A ESTRUTURA MOBILIÁRIA, ENVERNIZADA COM ASSENTO REDONDO ESTOFADO EM CURVIM NA COR PRETA, DIÂMETRO APROXIMADO DE 35 CM, ALTURA APROXIMADA DE...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao: "Inventário do item gerado automaticamente par teste. Número 9",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 43,
    item: 1144,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000042",
    fornecedor: "PEZANI COMÉRCIO DE MÓVEIS EIRELI ME",
    empenho: "2017NE801976",
    identificador: "123456789",
    descricao:
      "BANQUETA PARA MESA DE DESENHO, FABRICADA EM MADEIRA ADEQUADA A ESTRUTURA MOBILIÁRIA, ENVERNIZADA COM ASSENTO REDONDO ESTOFADO EM CURVIM NA COR PRETA, DIÂMETRO APROXIMADO DE 35 CM, ALTURA APROXIMADA DE...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 42",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 56,
    item: 1196,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000055",
    fornecedor:
      "KARLA ADRIANA CONSTANTIN E CIA COMÉRCIO DE EQUIPAMENTOS DIDÁTICOS LTDA - EPP",
    empenho: "2017NE801981",
    identificador: "123456789",
    descricao:
      "TORSO MUSCULAR DE LUXO EM 31 PARTES. REPRESENTA A MUSCULATURA SUPERFICIAL E PROFUNDA.DESMONTÁVEL NAS SEGUINTES PARTES: CABEÇA EM 6 PARTES, PAREDES TORÁCICA E ABDOMINAL, COM A MUSCULATURA RESPECTIVA, V...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 55",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 50,
    item: 1202,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000049",
    fornecedor:
      "KARLA ADRIANA CONSTANTIN E CIA COMÉRCIO DE EQUIPAMENTOS DIDÁTICOS LTDA - EPP",
    empenho: "2017NE801981",
    identificador: "123456789",
    descricao:
      "OUVIDO, 3 VEZES O TAMANHO NATURAL, 3 PARTES. OUVIDO EXTERNO, MÉDIO E INTERNO. TÍMPANO REMOVÍVEL COM MARTELO E BIGORNA, BEM COMO O LABIRINTO COM ESTRIBOS EM 2 PARTES, CÓCLEA E NERVOS VESTIBULOCOCLEARES...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 49",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 26,
    item: 1205,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000025",
    fornecedor: "ARTFRIO INDUSTRIA E COMERCIO DE MOVEIS, ESQUADRIAS, ART",
    empenho: "2017NE801993",
    identificador: "123456789",
    descricao:
      "MESA LISA, CONFECCIONADA EM AÇO INO AISI 304 / 18 (1,2MM), LIGA 18.8, MEDINDO 1500X600X850MM, CONTENDO 4 GAVETAS COM CORREDIÇAS TELESCÓPICAS E PUXADORES, 02 PRATELEIRAS LISAS, ESTRUTURA TUBULAR COM 4 ...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 25",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 38,
    item: 1210,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000037",
    fornecedor: "ROBERTO WAGNER MARQUES - ME",
    empenho: "2017NE802015",
    identificador: "123456789",
    descricao:
      "BANHO ULTRASSÔNICO, CAPACIDADE DA CUBA ENTRE 2 E 3 LITROS, TEMPORIZADOR DE 0 A 30 MIN, SEM AQUECIMENTO, COM DRENO, GRADE PERFURADA, 40 KHZ, 100 - 150 W RMS, RUÍDO MÁXIMO 75 DB, 110/220 V, 50/60 HZ, 60...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 37",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 45,
    item: 1220,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000044",
    fornecedor: "POLUX COMERCIAL EIRELI EPP",
    empenho: "2017NE802013",
    identificador: "123456789",
    descricao:
      "MARCA: IBRAMED ; 1 TELA DE FILTRO; 1 APLICADOR ADAPTADOR COM ROSCA; 1 MANGUEIRA ESPIRALADA; 1 APLICADOR VENTOSA DE VIDRO FACIAL LUNETA DE 18MM; 1 APLICADOR VENTOSA DE VIDRO FACIAL LUNETA DE 12MM; 1 AP...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 44",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 53,
    item: 1234,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000052",
    fornecedor: "LIMATEC INDÚSTRIA E SERVIÇOS EIRELI EPP",
    empenho: "2016NE801107",
    identificador: "123456789",
    descricao:
      "ESTUFA INCUBADORA TIPO BOD CONST.GAB. TIPO GELADEIRA COM ISOLACAO TERMICA EM POLIURETANO EXPANDIDO ACABAMENTO CHAPA PINTADO COR BRANCA, PAINEL FRONTAL FACILITANDO ACESSO E VISUALIZACAO INSTALADO PARTE...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 52",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 87,
    item: 1272,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000086",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 86",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 29,
    item: 1276,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000028",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 28",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 61,
    item: 1292,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000060",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 60",
    localizacao: "",
    usuario: "david4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 11,
    item: 1297,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000010",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 10",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 4,
    item: 1317,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000003",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao: "Inventário do item gerado automaticamente par teste. Número 3",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 59,
    item: 1337,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000058",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 58",
    localizacao: "",
    usuario: "jeff",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 66,
    item: 1340,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000065",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 65",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 20,
    item: 1346,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000019",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 19",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 86,
    item: 1348,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000085",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 85",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 27,
    item: 1380,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000026",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 2,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 26",
    localizacao: "",
    usuario: "caetano4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 18,
    item: 1424,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000017",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 17",
    localizacao: "",
    usuario: "novo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 5,
    item: 1455,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000004",
    fornecedor: "M&R EQUIPAMENTOS E MOVEIS LTDA - ME",
    empenho: "2019NE802029",
    identificador: "123456789",
    descricao:
      "BANQUETA ALTA PARA LABORATÓRIO, ASSENTO EM ESPUMA INJETADA COM 25 MM DE ESPESSURA, DIÂMETRO 40CM, EM COURO SINTÉTICO NA COR PRETA, ESTRUTURA  DE AÇO TUBULAR DE 7/8 POL, COM APOIO PARA OS PÉS, PINTURA ...",
    situacao: 1,
    estadoPlaqueta: 3,
    observacao: "Inventário do item gerado automaticamente par teste. Número 4",
    localizacao: "",
    usuario: "puppo",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
  {
    id: 17,
    item: 1473,
    inventario: 1,
    dependencia: 2,
    departamento: 2,
    patrimonio: "000016",
    fornecedor: "MILAN MOVEIS INDUSTRIA E COMERCIO LTDA",
    empenho: "2020NE800452",
    identificador: "123456789",
    descricao:
      "CARTEIRA UNIVERSITÁRIA COM PRANCHETA LATERAL ESCAMOTEÁVEL E APOIO PARA O BRAÇO. COR AZUL, REVESTIDA EM COURO SINTÉTICO. MARCA: MILAN",
    situacao: 1,
    estadoPlaqueta: 1,
    observacao:
      "Inventário do item gerado automaticamente par teste. Número 16",
    localizacao: "",
    usuario: "diana4",
    dataCadastro: "04/07/2022",
    dataAtualizacao: "04/07/2022",
  },
]);
</script>
